#!/usr/bin/env bash
# ============================================================
#  Deploy site/ to wwwebtech.in on Hostinger shared hosting.
#
#    tools/deploy.sh              # back up, upload, verify
#    tools/deploy.sh --dry-run    # show what would change, upload nothing
#    tools/deploy.sh --rollback   # restore the most recent backup
#
#  Where it deploys TO lives in tools/deploy.env, which is gitignored —
#  this repository is public, and a host plus an account name is most of
#  what someone needs to start guessing at a password. Copy the sample:
#
#    cp tools/deploy.env.sample tools/deploy.env   # then fill it in
#
#  Auth, in order of preference:
#    1. SSH key at ~/.ssh/wwwebtech_deploy  (add the .pub in hPanel)
#    2. SSHPASS env var                     (export SSHPASS='...')
#
#  It ALWAYS takes a timestamped backup of the live site before
#  touching anything, so a bad deploy is one command away from undone.
# ============================================================
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ENVFILE="$REPO/tools/deploy.env"
if [[ -f "$ENVFILE" ]]; then
  # shellcheck disable=SC1090
  set -a; source "$ENVFILE"; set +a
fi
HOST="${DEPLOY_HOST:-}"
PORT="${DEPLOY_PORT:-65002}"
USER="${DEPLOY_USER:-}"
REMOTE_ROOT="${DEPLOY_REMOTE_ROOT:-}"
if [[ -z "$HOST" || -z "$USER" || -z "$REMOTE_ROOT" ]]; then
  echo "No deploy target. Copy tools/deploy.env.sample to tools/deploy.env and fill it in." >&2
  exit 2
fi

BACKUP_DIR="backups"
LOCAL="$REPO/site"
STAMP="$(date -u +%Y%m%d-%H%M%S)"

DRY=0; ROLLBACK=0
for a in "$@"; do
  case "$a" in
    --dry-run)  DRY=1 ;;
    --rollback) ROLLBACK=1 ;;
    *) echo "unknown option: $a" >&2; exit 2 ;;
  esac
done

SSH_BASE=(-p "$PORT" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=20)

# Prefer the key, but only if it actually authenticates — a key that exists
# locally and was never added in hPanel would otherwise fail the whole
# deploy while a working password sits unused in the environment.
KEY="$HOME/.ssh/wwwebtech_deploy"
KEY_WORKS=0
if [[ -f "$KEY" ]]; then
  if ssh "${SSH_BASE[@]}" -i "$KEY" -o IdentitiesOnly=yes -o BatchMode=yes \
       "$USER@$HOST" 'exit' >/dev/null 2>&1; then KEY_WORKS=1; fi
fi

if [[ $KEY_WORKS -eq 1 ]]; then
  SSH_BASE+=(-i "$KEY" -o IdentitiesOnly=yes)
  RUN=(ssh); RSYNC_RSH="ssh ${SSH_BASE[*]}"
  echo "auth: ssh key"
elif [[ -n "${SSHPASS:-}" ]]; then
  command -v sshpass >/dev/null || { echo "sshpass not installed" >&2; exit 1; }
  RUN=(sshpass -e ssh); RSYNC_RSH="sshpass -e ssh ${SSH_BASE[*]}"
  echo "auth: password (SSHPASS)"
else
  echo "No credentials. Either add ~/.ssh/wwwebtech_deploy, or: export SSHPASS='...'" >&2
  exit 1
fi

sshx() { "${RUN[@]}" "${SSH_BASE[@]}" "$USER@$HOST" "$@"; }

# --- connectivity -------------------------------------------------------
echo "checking connection..."
sshx 'echo ok' >/dev/null || { echo "cannot authenticate to $USER@$HOST:$PORT" >&2; exit 1; }

# --- rollback -----------------------------------------------------------
if [[ $ROLLBACK -eq 1 ]]; then
  LATEST=$(sshx "ls -1d $BACKUP_DIR/public_html-* 2>/dev/null | tail -1" || true)
  [[ -n "$LATEST" ]] || { echo "no backup found on the server" >&2; exit 1; }
  echo "restoring $LATEST"
  sshx "rm -rf '$REMOTE_ROOT' && cp -a '$LATEST' '$REMOTE_ROOT'"
  echo "rolled back."
  exit 0
fi

# --- backup the live site ----------------------------------------------
echo "backing up live site -> $BACKUP_DIR/public_html-$STAMP"
sshx "mkdir -p '$BACKUP_DIR' && [ -d '$REMOTE_ROOT' ] && cp -a '$REMOTE_ROOT' '$BACKUP_DIR/public_html-$STAMP' || true"
sshx "ls -1d $BACKUP_DIR/public_html-* 2>/dev/null | head -20 | sed 's/^/  /'" || true
# keep the five most recent backups
sshx "ls -1dt $BACKUP_DIR/public_html-* 2>/dev/null | tail -n +6 | xargs -r rm -rf" || true

# --- upload -------------------------------------------------------------
# --- Paths inside public_html that this repo does NOT own -------------
#  `--delete` removes anything on the server that is not in site/. These
#  directories live inside the web root but are not part of the static
#  site, so without these exclusions a deploy would silently destroy them:
#
#    /flow/       document root of the flow.wwwebtech.in subdomain
#    /admin/      the automation panel     (automation/webroot/admin)
#    /api/        the automation endpoints (automation/webroot/api)
#    /_wwt.php    the private-path finder  (automation/webroot)
#    /serve.php   the AI-crawler logger    (automation/webroot)
#    /lp/         the landing pages        (automation/webroot/lp)
#    /tools/      the free website audit    (automation/webroot/tools)
#    /llms*.txt   regenerated by the SEO job
#
#  Generated blog posts live at /blog/<slug>/ alongside hand-written ones, so
#  they CANNOT be excluded by name. They are rebuilt from the database after
#  the upload instead — see the republish step at the end of this script.
#
#  Add to this list BEFORE adding anything server-managed to the web root.
KEEP=(--exclude '/flow/' --exclude '/admin/' --exclude '/api/'
      --exclude '/_wwt.php' --exclude '/serve.php' --exclude '/lp/'
      --exclude '/tools/'
      --exclude '/llms.txt' --exclude '/llms-full.txt'
      --exclude '/.well-known/')

# Reading the list above and remembering to update it is exactly the step
# that has been missed before — twice, and both times the deploy deleted
# something live. So the list is checked against reality instead: every
# top-level entry in automation/webroot/ must be excluded here, or this
# refuses to run.
missing=()
for entry in "$REPO/automation/webroot/"*; do
  [ -e "$entry" ] || continue
  name="/$(basename "$entry")"
  [ -d "$entry" ] && name="$name/"
  printf '%s\n' "${KEEP[@]}" | grep -qxF "$name" || missing+=("$name")
done
if [ ${#missing[@]} -gt 0 ]; then
  echo "REFUSING TO DEPLOY: these live in the web root but are not excluded," >&2
  echo "so --delete would remove them from the server:" >&2
  printf '  %s\n' "${missing[@]}" >&2
  echo "Add them to KEEP in $0." >&2
  exit 1
fi

RSYNC_FLAGS=(-az --delete --human-readable --info=stats2
             --exclude '.DS_Store' --exclude '.git' "${KEEP[@]}")
[[ $DRY -eq 1 ]] && RSYNC_FLAGS+=(--dry-run --itemize-changes)

echo "uploading $LOCAL/ -> $REMOTE_ROOT/"
rsync "${RSYNC_FLAGS[@]}" -e "$RSYNC_RSH" "$LOCAL/" "$USER@$HOST:$REMOTE_ROOT/"

[[ $DRY -eq 1 ]] && { echo "dry run — nothing changed."; exit 0; }

# --- permissions --------------------------------------------------------
sshx "cd '$REMOTE_ROOT' && find . -type d -exec chmod 755 {} + && find . -type f -exec chmod 644 {} +"

# --- verify -------------------------------------------------------------
echo
echo "verifying https://wwwebtech.in ..."
fail=0
check() {
  local path="$1" want="$2"
  local got; got=$(curl -s -o /dev/null -w '%{http_code}' -m 20 "https://wwwebtech.in$path")
  printf "  %-34s %s (want %s)%s\n" "$path" "$got" "$want" \
    "$([[ "$got" == "$want" ]] && echo '' || { fail=1; echo '   <-- MISMATCH'; })"
}
check "/"                              200
check "/services/web-development/"     200
check "/blog/"                         200
check "/contact/"                      200
check "/definitely-not-a-page"         404
# The subdomain shares this web root; a deploy that deletes it is the
# failure this script exists to make impossible. Verify, don't assume.
fl=$(curl -s -o /dev/null -w '%{http_code}' -m 20 https://flow.wwwebtech.in/ || echo 000)
printf "  %-34s %s (want 2xx/3xx)%s\n" "flow.wwwebtech.in" "$fl" \
  "$([[ "$fl" =~ ^[23] ]] && echo '' || { fail=1; echo '   <-- SUBDOMAIN AFFECTED'; })"
printf "  %-34s %s\n" "/services/website-development" \
  "$(curl -s -o /dev/null -w '%{http_code} -> %{redirect_url}' -m 20 https://wwwebtech.in/services/website-development)"

# --- rebuild what the automation layer owns --------------------------
#  A deploy overwrites the blog index, the homepage teasers and the sitemap
#  with the freshly built versions, which know nothing about posts published
#  on the server. The database does. Rebuilding from it puts them back.
#
#  Skipped silently when the automation layer is not installed.
echo
echo "rebuilding server-generated pages..."
sshx "test -f wwt_private/cron/run.php && /usr/bin/php wwt_private/cron/run.php republish_all 2>&1 | sed 's/^/  /' || echo '  (automation layer not installed — skipped)'" || true

echo
if [[ $fail -eq 0 ]]; then
  echo "deployed OK. Backup on server: $BACKUP_DIR/public_html-$STAMP"
  echo "Roll back with: tools/deploy.sh --rollback"
else
  echo "DEPLOYED BUT CHECKS FAILED — consider: tools/deploy.sh --rollback" >&2
  exit 1
fi
